version: '3'

services:
  my-laravel-app:
    image: factory-webshop-api
    ports:
      - "8000:8000"
    container_name: my-laravel-app
    networks:
      - factory
    environment:
      DB_USER: root
      DB_PASSWORD: root_password

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: factory-webshop-db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - factory

networks:
  factory:
    external: true